alastor/articles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import ArticleListEditionView, ArticleListView, \
    SectionListView, ArticleDetailView


urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='index'),
    url(r'^seccion/(?P<slug>[-\w]+)/$',
        SectionListView.as_view(), name='section'),
    url(r'^edicion/(?P<number>[-\w]+)/$',
        ArticleListEditionView.as_view(), name='edition'),
    url(r'^articulo/(?P<slug>[-\w]+)/$',
        ArticleDetailView.as_view(), name='detail')
]

alastor/authors/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import AuthorDetailView


urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', AuthorDetailView.as_view(), name='detail'),
]

alastor/publications/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import PublicationList


urlpatterns = [
    url(r'^$', PublicationList.as_view(), name='index'),
]

config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
# from django.contrib.flatpages import views as flatpage_views

urlpatterns = [
    url(r'^', include(('alastor.articles.urls', 'articles'),
        namespace='articles')),
    url(r'^autor/', include(('alastor.authors.urls', 'authors'),
        namespace='authors')),
    url(r'^publicaciones/',
        include(('alastor.publications.urls', 'publications'),
                namespace='publications')),
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^ckeditor/', include(
        ('ckeditor_uploader.urls', 'ckeditor_uploader'))),
    url(r'^select2/', include(
        ('django_select2.urls', 'django_select2'))),

    # Your stuff: custom urls includes go here

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar
    urlpatterns += [
        # url(r'^presentacion/$', flatpage_views.flatpage, {'url': '/presentacion/'}, name='presentation'),
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

alastor/articles/models.py
from django.urls import reverse
from django.db import models

from alastor.authors.models import Author
from alastor.editions.models import Edition


class Section(models.Model):
    name = models.CharField(max_length=140, verbose_name=u'Nombre')
    slug = models.SlugField(unique=True, verbose_name=u'Link de enlace')

    def get_absolute_url(self):
        return reverse('articles:section', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = u'Sección'
        verbose_name_plural = u'Secciones'

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=140, verbose_name=u'Título')
    slug = models.SlugField(unique=True, verbose_name=u'Link de enlace')

    introduction = models.TextField(
        blank=True, verbose_name=u'Introducción/Entradilla')
    body = models.TextField(verbose_name=u'Texto')
    is_translation = models.BooleanField(
        verbose_name=u'Traducción', default=False)
    translation_body = models.TextField(
        blank=True, verbose_name=u'Texto traducido')
    translator = models.ForeignKey(
        Author,
        verbose_name=u'Traductor', null=True,
        blank=True, related_name='article_translator',
        on_delete=models.CASCADE
    )
    section = models.ForeignKey(
        Section, verbose_name=u'Sección',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        Author, verbose_name=u'Autor',
        on_delete=models.CASCADE
    )
    edition = models.ForeignKey(
        Edition, verbose_name=u'Edición',
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='article', blank=True,
                              verbose_name=u'Imagen de texto')
    image_caption = models.TextField(
        blank=True, verbose_name=u'Descripción de imagen'
    )

    def get_absolute_url(self):
        return reverse('articles:detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = u'Artículo'
        verbose_name_plural = u'Artículos'

    def __str__(self):
        return self.title


class ImageArticle(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='article',
                              verbose_name=u'Imagen de galería')
    image_caption = models.TextField(
        blank=True, verbose_name=u'Descripción de imagen'
    )

    class Meta:
        verbose_name = u'Imagen de galería'
        verbose_name_plural = u'Imagenes de galería'

    def __str__(self):
        return "{} - {}".format(self.article, self.pk)

alastor/authors/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=140, verbose_name=u'Nombre')
    photo = models.ImageField(upload_to='author', blank=True,
                              verbose_name=u'Foto')
    bio = models.TextField(blank=True, verbose_name=u'Biografía')
    promote = models.BooleanField(
        default=False, verbose_name=u'Promover',
        help_text=u'Promover autor como autor destacado en index'
    )

    class Meta:
        verbose_name = u'Autor'
        verbose_name_plural = u'Autores'
        ordering = ['-promote', 'name']

    def __str__(self):
        return self.name

alastor/editions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse


class Edition(models.Model):
    number = models.PositiveIntegerField(verbose_name=u'Número', unique=True)
    publication_date = models.DateField(
        verbose_name=u'Fecha de edición',
        null=True,
        blank=True
    )
    cover = models.ImageField(upload_to='edition', blank=True,
                              verbose_name=u'Portada')

    draft = models.BooleanField(verbose_name='Borrador', default=True)

    class Meta:
        ordering = ('-number',)
        verbose_name = u'Edición'
        verbose_name_plural = u'Ediciones'

    def get_date(self):
        return self.publication_date.strftime('%b %Y')

    def get_absolute_url(self):
        return reverse('articles:edition', kwargs={'number': self.number})

    def __str__(self):
        return '{0} - {1}'.format(
            self.number,
            self.get_date()
        )

alastor/publications/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from alastor.editions.models import Edition
from alastor.authors.models import Author


class Publication(models.Model):
    name = models.CharField(max_length=140, verbose_name=u'Nombre')
    edition = models.ForeignKey(
        Edition, verbose_name=u'Edición',
        on_delete=models.CASCADE
    )
    cover = models.ImageField(upload_to='cover', blank=True,
                              verbose_name=u'Portada')
    author = models.ForeignKey(
        Author, verbose_name=u'Autor',
        on_delete=models.CASCADE
    )
    archivo = models.FileField(upload_to='publication',
                               verbose_name=u'Archivo')
    description = models.TextField(verbose_name=u'Descripción',
                                   blank=True)

    class Meta:
        verbose_name = u'Libro'
        verbose_name_plural = u'Libros'
        ordering = ('-edition__number', )

    def __str__(self):
        return self.name

alastor/articles/views.py
from django.views.generic import ListView, DetailView
from django.db.models import Count
from django.shortcuts import redirect
from alastor.editions.models import Edition
from .models import Article, Section, Author


class ArticleBaseView(ListView):
    model = Article
    template_name = 'articles/list.html'
    author_list = None

    def dispatch(self, request, *args, **kwargs):
        self.author_list = Author.objects.annotate(
            art_count=Count('article')).filter(art_count__gt=0)
        return super(ArticleBaseView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = super(ArticleBaseView, self).get_queryset()
        return qs.select_related('author')

    def get_context_data(self, **kwargs):
        context = super(ArticleBaseView, self).get_context_data(**kwargs)
        context['editions'] = Edition.objects.exclude(draft=True)
        for section in Section.objects.all():
            context.update({
                section.slug: context['object_list'].filter(section=section)
            })

        return context


class ArticleListView(ArticleBaseView):
    edition = None

    def get_queryset(self):
        qs = super(ArticleListView, self).get_queryset()
        # TODO Write an accurate way to get latest edition
        self.edition = Edition.objects.exclude(draft=True).first()
        return qs.filter(edition=self.edition)

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['author_list'] = self.author_list.filter(article__edition=self.edition)
        context['author_old'] = self.author_list.exclude(article__edition=self.edition)
        return context


class ArticleListEditionView(ArticleBaseView):

    def dispatch(self, request, *args, **kwargs):
        is_draft = Edition.objects.filter(
            number=self.kwargs['number'], draft=True).exists()
        if is_draft and not request.user.is_authenticated():
            return redirect('articles:index')
        return super(ArticleListEditionView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = super(ArticleListEditionView, self).get_queryset()
        return qs.filter(edition__number=self.kwargs['number'])

    def get_context_data(self, **kwargs):
        context = super(ArticleListEditionView, self).get_context_data(**kwargs)
        context['author_list'] = self.author_list.filter(
            article__edition__number=self.kwargs['number'])
        context['author_old'] = self.author_list.exclude(
            article__edition__number=self.kwargs['number'])
        return context


class SectionListView(ListView):
    model = Article
    template_name = 'articles/section.html'
    context_object_name = 'articles'

    def get_queryset(self):
        qs = super(SectionListView, self).get_queryset()
        return qs.filter(section__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(SectionListView, self).get_context_data(**kwargs)
        context['editions'] = Edition.objects.exclude(draft=True)
        # TODO Write an accurate way to get latest edition
        edition = Edition.objects.exclude(draft=True).first()
        context['edition_articles'] = context['articles'].select_related(
            'author').filter(edition=edition)
        context['old_articles'] = context['articles'].exclude(
            edition=edition).filter(edition__draft=False)

        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'articles/detail.html'
    context_object_name = 'article'

    def dispatch(self, request, *args, **kwargs):
        is_draft = self.get_object().edition.draft
        if is_draft and not request.user.is_authenticated():
            return redirect('articles:index')
        return super(ArticleDetailView, self).dispatch(request, *args, **kwargs)

alastor/authors/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import Author


class AuthorDetailView(DetailView):
    model = Author
    context_object_name = 'author'
    template_name = 'authors/detail.html'

    def get_queryset(self):
        qs = super(AuthorDetailView, self).get_queryset()
        return qs.prefetch_related('article_set')

alastor/editions/views.py
from django.shortcuts import render

alastor/publications/views.py
from django.views.generic import ListView
from .models import Publication


class PublicationList(ListView):
    model = Publication
    template_name = 'publications/list.html'
    context_object_name = 'publications'

    def get_queryset(self):
        qs = super(PublicationList, self).get_queryset()
        return qs.filter(edition__draft=False)

alastor/templates/articles/detail.html
{% extends "base.html" %}
{% load static thumbnail %}
{% block meta %}
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@alastorliteral" />
  <meta name="twitter:title" content="{{ article.title }}" />
  <meta name="twitter:description" content="{{ article.introduction|safe }}" />
  {% if article.image %}
  <meta name="twitter:image" content="{{ article.image.url }}" />
  {% endif %}

  <meta property="og:url" content="{{ article.get_absolute_url }}" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="{{ article.title }}" />
  <meta property="og:description" content="{{ article.introduction|safe }}" />
  {% if article.image %}
  <meta property="og:image" content="{{ article.image.url }}" />
  {% endif %}
{% endblock meta %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.0/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.0/slick/slick-theme.css"/>
{% endblock %}
{% block content %}
<article class="main-article">
  <header class="text-center">
    <p class="article-section-title article-info"><a href="{{ article.section.get_absolute_url }}">{{ article.section.name }}</a></p>
    <p class="article-info"><a href="{{ article.edition.get_absolute_url }}">No. {{ article.edition.number }}</a></p>
    <h2>{{ article.title }}</h2>
    <p class="article-author">Por <a href="{% url 'authors:detail' article.author.id %}">{{ article.author.name }}</a></p>
  </header>
  <div class="content">
    <section class="introduction">
      {{ article.introduction|safe }}
    </section>
    <figure class="article-img">
      {% thumbnail article.image "700" as im %}
        <img src="{{ im.url }}" class="img-responsive center-block">
      {% endthumbnail %}
      {% if article.image_caption %}<figcaption class="text-center image-caption">{{ article.image_caption|safe }}</figcaption>{% endif %}
    </figure>
    <section class="body">
      {% if article.is_translation %}
      <div class="row">
        <div class="col-md-6">{{ article.translation_body|safe }}</div>
        <div class="col-md-6">{{ article.body|safe }}</div>
      </div>
      {% else %}
        {{ article.body|safe }}
      {% endif %}

      {% if article.imagearticle_set.count %}
        <div class="gallery">
          {% for i in article.imagearticle_set.all %}
            <div>
              {% thumbnail i.image "x600" as im %}
                <img src="{{ im.url }}" class="img-responsive" />
              {% endthumbnail %}
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </section>
  </div>
  <footer>
    <div class="share-icons">
      <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
      <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
    </div>
    <section class="author-bio">
      {% if article.translator %}
        <h3>Traductor: <a href="#">{{ article.translator.name }}</a></h3>
        <figure class="pull-left">
          {% thumbnail article.translator.photo "100x100" crop="center" as im %}
            <a href="#"><img src="{{ im.url }}" class="img-responsive img-circle"></a>
          {% endthumbnail %}
        </figure>
        {{ article.translator.bio|safe }}
        <div class="clearfix"></div>
        <hr>
      {% endif %}
      <h3>{% if article.translator %}Autor: {% endif %}<a href="#">{{ article.author.name }}</a></h3>
      <figure class="pull-left">
        {% thumbnail article.author.photo "100x100" crop="center" as im %}
          <a href="#"><img src="{{ im.url }}" class="img-responsive img-circle"></a>
        {% endthumbnail %}
      </figure>
      {{ article.author.bio|safe }}
    </section>
    <div class="clearfix"></div>
  </footer>
</article>
{% endblock %}
{% block javascript %}
  <script type="text/javascript" src="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.0/slick/slick.min.js"></script>
  <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
      $('.gallery').slick({
        dots: true,
        infinite: true,
        speed: 300,
        variableWidth: true,
        centerMode: true,
      });
    });
  </script>
{% endblock %}

alastor/templates/articles/grid.html
{% load thumbnail %}
<div class="row">
  {% if type == 'full' %}
    {% for article in articles %}
    <div class="col-xs-12">
      <div class="row">
        <div class="col-sm-6 col-xs-12">
          <figure>
            {% thumbnail article.image "600x300" crop="center" as im %}
              <a href="{{ article.get_absolute_url }}"><img src="{{ im.url }}" class="img-responsive"></a>
            {% endthumbnail %}
          </figure>
        </div>
        <div class="col-sm-6 col-xs-12">
          <section class="text-center full-section">
            <h3 class="grid-title"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
            <p class="grid-author">Por <a href="{% url 'authors:detail' article.author.id %}">{{ article.author }}</a></p>
            <p>{{ article.introduction|safe|truncatewords:20 }}</p>
          </section>
        </div>
      </div>
    </div>
    {% endfor %}
  {% elif type == 'double' %}
    {% for article in articles %}
      <div class="col-sm-6 col-xs-12">
        <figure>
          {% thumbnail article.image "600x300" crop="center" as im %}
            <a href="{{ article.get_absolute_url }}"><img src="{{ im.url }}" class="img-responsive"></a>
          {% endthumbnail %}
        </figure>
        <section class="text-center">
          <h3 class="grid-title"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
          <p class="grid-author">Por <a href="{% url 'authors:detail' article.author.id %}">{{ article.author }}</a></p>
          <p>{{ article.introduction|safe|truncatewords:20 }}</p>
        </section>
      </div>
      {% cycle '' '<div class="clearfix"></div>' %}
    {% endfor %}
  {% else %}
    {% for article in articles %}
      <div class="col-sm-4 col-xs-12">
        <figure>
          {% thumbnail article.image "600x300" crop="center" as im %}
            <a href="{{ article.get_absolute_url }}"><img src="{{ im.url }}" class="img-responsive"></a>
          {% endthumbnail %}
        </figure>
        <section class="text-center">
          <h3 class="grid-title"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
          <p class="grid-author">Por <a href="{% url 'authors:detail' article.author.id %}">{{ article.author }}</a></p>
          <p>{{ article.introduction|safe|truncatewords:20 }}</p>
        </section>
      </div>
      {% cycle '' '' '<div class="clearfix"></div>' %}
    {% endfor %}
  {% endif %}
</div>

alastor/templates/articles/list.html
{% extends "base.html" %}
{% load thumbnail articles_tags %}
{% block content %}
<div class="version-list">
  {% for edition in editions %}
    <div class="version-box">
      <a href="{{ edition.get_absolute_url }}">
        <figure>
          {% thumbnail edition.cover "80x80" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
        </figure>
        <p class="edition-number">No. {{ edition.number }}</p>
        <p class="edition-date">{{ edition.get_date }}</p>
      </a>
    </div>
  {% endfor %}
</div>
<div class="content">
  {% if narrativa %}
  <section class="section">
    <h2 class="section-title no-margin-top">~ Narrativa ~</h2>
    {% show_grid narrativa %}
  </section>
  {% endif %}
  {% if poesia %}
  <section class="section">
    <h2 class="section-title">~ Poesía ~</h2>
    {% show_grid poesia %}
  </section>
  {% endif %}
  {% if impresiones %}
  <section class="section">
    <h2 class="section-title">~ Impresiones ~</h2>
    {% show_grid impresiones %}
  </section>
  {% endif %}
  {% if resena %}
  <section class="section">
    <h2 class="section-title">~ Reseña ~</h2>
    {% show_grid resena %}
  </section>
  {% endif %}
  {% if ensayo %}
  <section class="section">
    <h2 class="section-title">~ Ensayo ~</h2>
    {% show_grid ensayo %}
  </section>
  {% endif %}
</div>
{% include "authors/author_block.html" %}
{% endblock %}

alastor/templates/articles/section.html
{% extends "base.html" %}
{% load thumbnail articles_tags %}
{% block content %}
<div class="version-list">
  {% for edition in editions %}
    <div class="version-box">
      <a href="{{ edition.get_absolute_url }}">
        <figure>
          {% thumbnail edition.cover "80x80" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
        </figure>
        <p class="edition-number">No. {{ edition.number }}</p>
        <p class="edition-date">{{ edition.get_date }}</p>
      </a>
    </div>
  {% endfor %}
</div>
<div class="content">
  <section class="section">
    <div class="row">
      {% for article in edition_articles %}
        <div class="col-xs-12 section-block">
          <div class="row">
            <div class="col-sm-6 col-xs-12">
              <figure>
                {% thumbnail article.image "600x300" crop="center" as im %}
                  <a href="{{ article.get_absolute_url }}"><img src="{{ im.url }}" class="img-responsive"></a>
                {% endthumbnail %}
              </figure>
            </div>
            <div class="col-sm-6 col-xs-12">
              <section class="text-center full-section">
                <h3 class="grid-title"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
                <p class="grid-author">Por <a href="{% url 'authors:detail' article.author.id %}">{{ article.author }}</a></p>
                <p>{{ article.introduction|safe|truncatewords:20 }}</p>
              </section>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>
  {% if old_articles %}
    <section class="section">
      <h2 class="previous-title">Publicado en otras ediciones</h2>
      <div class="row">
        {% for article in old_articles %}
          <div class="col-sm-4 col-xs-12">
            <figure>
              {% thumbnail article.image "600x300" crop="center" as im %}
                <a href="{{ article.get_absolute_url }}"><img src="{{ im.url }}" class="img-responsive"></a>
              {% endthumbnail %}
            </figure>
            <section class="text-center">
              <h3 class="grid-title"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
              <p class="grid-author">Por <a href="">{{ article.author }}</a></p>
              <p>{{ article.introduction|safe|truncatewords:20 }}</p>
            </section>
          </div>
        {% endfor %}
      </div> 
    </section>
  {% endif %}
</div>
{% endblock %}