alastor/articles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import ArticleListEditionView, ArticleListView, \
    SectionListView, ArticleDetailView


urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='index'),
    url(r'^seccion/(?P<slug>[-\w]+)/$',
        SectionListView.as_view(), name='section'),
    url(r'^edicion/(?P<number>[-\w]+)/$',
        ArticleListEditionView.as_view(), name='edition'),
    url(r'^articulo/(?P<slug>[-\w]+)/$',
        ArticleDetailView.as_view(), name='detail')
]

alastor/authors/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import AuthorDetailView


urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', AuthorDetailView.as_view(), name='detail'),
]

alastor/publications/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import PublicationList


urlpatterns = [
    url(r'^$', PublicationList.as_view(), name='index'),
]

config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
# from django.contrib.flatpages import views as flatpage_views

urlpatterns = [
    url(r'^', include(('alastor.articles.urls', 'articles'),
        namespace='articles')),
    url(r'^autor/', include(('alastor.authors.urls', 'authors'),
        namespace='authors')),
    url(r'^publicaciones/',
        include(('alastor.publications.urls', 'publications'),
                namespace='publications')),
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^ckeditor/', include(
        ('ckeditor_uploader.urls', 'ckeditor_uploader'))),
    url(r'^select2/', include(
        ('django_select2.urls', 'django_select2'))),

    # Your stuff: custom urls includes go here

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    import debug_toolbar
    urlpatterns += [
        # url(r'^presentacion/$', flatpage_views.flatpage, {'url': '/presentacion/'}, name='presentation'),
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

alastor/articles/models.py
from django.urls import reverse
from django.db import models

from alastor.authors.models import Author
from alastor.editions.models import Edition


class Section(models.Model):
    name = models.CharField(max_length=140, verbose_name=u'Nombre')
    slug = models.SlugField(unique=True, verbose_name=u'Link de enlace')

    def get_absolute_url(self):
        return reverse('articles:section', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = u'Sección'
        verbose_name_plural = u'Secciones'

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=140, verbose_name=u'Título')
    slug = models.SlugField(unique=True, verbose_name=u'Link de enlace')

    introduction = models.TextField(
        blank=True, verbose_name=u'Introducción/Entradilla')
    body = models.TextField(verbose_name=u'Texto')
    is_translation = models.BooleanField(
        verbose_name=u'Traducción', default=False)
    translation_body = models.TextField(
        blank=True, verbose_name=u'Texto traducido')
    translator = models.ForeignKey(
        Author,
        verbose_name=u'Traductor', null=True,
        blank=True, related_name='article_translator',
        on_delete=models.CASCADE
    )
    section = models.ForeignKey(
        Section, verbose_name=u'Sección',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        Author, verbose_name=u'Autor',
        on_delete=models.CASCADE
    )
    edition = models.ForeignKey(
        Edition, verbose_name=u'Edición',
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='article', blank=True,
                              verbose_name=u'Imagen de texto')
    image_caption = models.TextField(
        blank=True, verbose_name=u'Descripción de imagen'
    )

    def get_absolute_url(self):
        return reverse('articles:detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = u'Artículo'
        verbose_name_plural = u'Artículos'

    def __str__(self):
        return self.title


class ImageArticle(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='article',
                              verbose_name=u'Imagen de galería')
    image_caption = models.TextField(
        blank=True, verbose_name=u'Descripción de imagen'
    )

    class Meta:
        verbose_name = u'Imagen de galería'
        verbose_name_plural = u'Imagenes de galería'

    def __str__(self):
        return "{} - {}".format(self.article, self.pk)

alastor/authors/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=140, verbose_name=u'Nombre')
    photo = models.ImageField(upload_to='author', blank=True,
                              verbose_name=u'Foto')
    bio = models.TextField(blank=True, verbose_name=u'Biografía')
    promote = models.BooleanField(
        default=False, verbose_name=u'Promover',
        help_text=u'Promover autor como autor destacado en index'
    )

    class Meta:
        verbose_name = u'Autor'
        verbose_name_plural = u'Autores'
        ordering = ['-promote', 'name']

    def __str__(self):
        return self.name

alastor/editions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse


class Edition(models.Model):
    number = models.PositiveIntegerField(verbose_name=u'Número', unique=True)
    publication_date = models.DateField(
        verbose_name=u'Fecha de edición',
        null=True,
        blank=True
    )
    cover = models.ImageField(upload_to='edition', blank=True,
                              verbose_name=u'Portada')

    draft = models.BooleanField(verbose_name='Borrador', default=True)

    class Meta:
        ordering = ('-number',)
        verbose_name = u'Edición'
        verbose_name_plural = u'Ediciones'

    def get_date(self):
        return self.publication_date.strftime('%b %Y')

    def get_absolute_url(self):
        return reverse('articles:edition', kwargs={'number': self.number})

    def __str__(self):
        return '{0} - {1}'.format(
            self.number,
            self.get_date()
        )

alastor/publications/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from alastor.editions.models import Edition
from alastor.authors.models import Author


class Publication(models.Model):
    name = models.CharField(max_length=140, verbose_name=u'Nombre')
    edition = models.ForeignKey(
        Edition, verbose_name=u'Edición',
        on_delete=models.CASCADE
    )
    cover = models.ImageField(upload_to='cover', blank=True,
                              verbose_name=u'Portada')
    author = models.ForeignKey(
        Author, verbose_name=u'Autor',
        on_delete=models.CASCADE
    )
    archivo = models.FileField(upload_to='publication',
                               verbose_name=u'Archivo')
    description = models.TextField(verbose_name=u'Descripción',
                                   blank=True)

    class Meta:
        verbose_name = u'Libro'
        verbose_name_plural = u'Libros'
        ordering = ('-edition__number', )

    def __str__(self):
        return self.name

alastor/articles/views.py
from django.views.generic import ListView, DetailView
from django.db.models import Count
from django.shortcuts import redirect
from alastor.editions.models import Edition
from .models import Article, Section, Author


class ArticleBaseView(ListView):
    model = Article
    template_name = 'articles/list.html'
    author_list = None

    def dispatch(self, request, *args, **kwargs):
        self.author_list = Author.objects.annotate(
            art_count=Count('article')).filter(art_count__gt=0)
        return super(ArticleBaseView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = super(ArticleBaseView, self).get_queryset()
        return qs.select_related('author')

    def get_context_data(self, **kwargs):
        context = super(ArticleBaseView, self).get_context_data(**kwargs)
        context['editions'] = Edition.objects.exclude(draft=True)
        for section in Section.objects.all():
            context.update({
                section.slug: context['object_list'].filter(section=section)
            })

        return context


class ArticleListView(ArticleBaseView):
    edition = None

    def get_queryset(self):
        qs = super(ArticleListView, self).get_queryset()
        # TODO Write an accurate way to get latest edition
        self.edition = Edition.objects.exclude(draft=True).first()
        return qs.filter(edition=self.edition)

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['author_list'] = self.author_list.filter(article__edition=self.edition)
        context['author_old'] = self.author_list.exclude(article__edition=self.edition)
        return context


class ArticleListEditionView(ArticleBaseView):

    def dispatch(self, request, *args, **kwargs):
        is_draft = Edition.objects.filter(
            number=self.kwargs['number'], draft=True).exists()
        if is_draft and not request.user.is_authenticated():
            return redirect('articles:index')
        return super(ArticleListEditionView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = super(ArticleListEditionView, self).get_queryset()
        return qs.filter(edition__number=self.kwargs['number'])

    def get_context_data(self, **kwargs):
        context = super(ArticleListEditionView, self).get_context_data(**kwargs)
        context['author_list'] = self.author_list.filter(
            article__edition__number=self.kwargs['number'])
        context['author_old'] = self.author_list.exclude(
            article__edition__number=self.kwargs['number'])
        return context


class SectionListView(ListView):
    model = Article
    template_name = 'articles/section.html'
    context_object_name = 'articles'

    def get_queryset(self):
        qs = super(SectionListView, self).get_queryset()
        return qs.filter(section__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(SectionListView, self).get_context_data(**kwargs)
        context['editions'] = Edition.objects.exclude(draft=True)
        # TODO Write an accurate way to get latest edition
        edition = Edition.objects.exclude(draft=True).first()
        context['edition_articles'] = context['articles'].select_related(
            'author').filter(edition=edition)
        context['old_articles'] = context['articles'].exclude(
            edition=edition).filter(edition__draft=False)

        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'articles/detail.html'
    context_object_name = 'article'

    def dispatch(self, request, *args, **kwargs):
        is_draft = self.get_object().edition.draft
        if is_draft and not request.user.is_authenticated():
            return redirect('articles:index')
        return super(ArticleDetailView, self).dispatch(request, *args, **kwargs)

alastor/authors/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import Author


class AuthorDetailView(DetailView):
    model = Author
    context_object_name = 'author'
    template_name = 'authors/detail.html'

    def get_queryset(self):
        qs = super(AuthorDetailView, self).get_queryset()
        return qs.prefetch_related('article_set')

alastor/editions/views.py
from django.shortcuts import render

alastor/publications/views.py
from django.views.generic import ListView
from .models import Publication


class PublicationList(ListView):
    model = Publication
    template_name = 'publications/list.html'
    context_object_name = 'publications'

    def get_queryset(self):
        qs = super(PublicationList, self).get_queryset()
        return qs.filter(edition__draft=False)

alastor/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Alastor{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Revista de literatura">
    <meta name="author" content="Yader Velasquez">

    {% block meta %}
    {% endblock %}

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}

  </head>

  <body>
    <div class="container">
      <header>
        <div class="top-header">
          <div class="secondary-menu pull-left">
            <ul>
              <li><a href="/presentacion/">Presentación</a></li> |
              <li><a href="{% url 'publications:index' %}">Libros</a></li>
            </ul>
          </div>
          <div class="social-menu pull-right">
            <ul>
              <li><a href="https://www.facebook.com/alastorliterario/"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
              <li><a href="https://twitter.com/AlastorRevista"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
            </ul>
          </div>
        </div>
        <h1><a href="/"><img src="{% static 'images/logo.png'%}" />Álastor</a></h1>
        <nav class="navbar navbar-default">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#top-menu">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="top-menu">
            <p class="mobile-section-header"><strong>Secciones</strong></p>
            <ul class="nav navbar-nav">
              {% for section in nav_sections %}
                <li><a href="{{ section.get_absolute_url }}">{{ section.name }}</a></li>
              {% endfor %}
            </ul>
            <p class="mobile-section-header"><strong>Ediciones</strong></p>
            <ul class="nav navbar-nav edition-mobile">
            {% for edition in editions %}
              <li><a href="{{ edition.get_absolute_url }}">{{ edition.number }} - {{ edition.get_date }}</a></li>
            {% endfor %}
            </ul>
          </div>
        </nav>
      </header>
      <main role="main">
      {% block content %}
      {% endblock %}
      </main>
      <footer class="footer">
        <div class="pull-right">
          <p>
            <a href="https://twitter.com/AlastorRevista"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
            <a href="https://www.facebook.com/alastorliterario/"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
            Alastor - 2016
          </p>
        </div>
      </footer>
    </div>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-80685359-1', 'auto');
      ga('send', 'pageview');
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>
    <script charset="utf-8">
      if ($('.version-list').length) {
        $('.version-list').slick({
          slidesToShow: 6,
          slidesToScroll: 2
        });
      }
    </script>
    <script type="text/javascript" charset="utf-8" src="{% static 'js/project.min.js' %}"></script>
    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>